info:
  version: v1.41.1
  title: data_source_huaweicloud_obs_bucket_object
  description:
schemes:
  - https
host: huaweicloud.com
tags:
  - name: OBS
paths:
  /{ObjectName}:
    head:
      tag: OBS
      operationId: GetObjectMetadata
    get:
      tag: OBS
      operationId: GetObject
