info:
  version: v1.xx.y
  title: data_source_huaweicloud_account
  description:
schemes:
  - https
host: huaweicloud.com
tags:
  - name: IAM
paths:
  /v3/auth/domains:
    get:
      tag: IAM
      operationId: List
