info:
  version: v1.xx.y
  title: data_source_huaweicloud_obs_buckets
  description:
schemes:
  - https
host: huaweicloud.com
tags:
  - name: OBS
paths:
  /:
    get:
      tag: OBS
      operationId: ListBuckets
    head:
      tag: OBS
      operationId: GetBucketMetadata
