info:
  version: v1.xx.y
  title: data_source_huaweicloud_csms_secret_version
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: kms
paths:
  /v1/{project_id}/secrets/{secretName}/versions/{versionID}:
    get:
      tag: kms
      operationId: ShowSecretVersion
  /v1/{project_id}/secrets/{secretName}/versions:
    get:
      tag: kms
      operationId: ListSecretVersions