info:
  version: 
  title: data_source_huaweicloud_compute_instances
  description: 
schemes:
  - https
host: huaweicloud.com
tags:
  - name: ECS
paths:
  /v1/{project_id}/cloudservers/detail:
    get:
      tag: ECS
      operationId: List
  /v1/{project_id}/cloudservers/{serverId}/block_device:
    get:
      tag: ECS
      operationId: List
  /v2/{project_id}/cloudvolumes/{id}:
    get:
      tag: EVS
      operationId: Get
  /v2.0/ports/{id}:
    get:
      tag: VPC
      operationId: Get
