info:
  version: v1.xx.y
  title: resource_huaweicloud_cce_addon
  description:
schemes:
  - https
host: huaweicloud.com
tags:
  - name: CCE
paths:
  /api/v3/addons/{id}:
    delete:
      tag: CCE
      operationId: Delete
    get:
      tag: CCE
      operationId: Get
    put:
      tag: CCE
      operationId: Update
  /api/v3/addons:
    post:
      tag: CCE
      operationId: Create
