info:
  version: v1.xx.y
  title: resource_huaweicloud_lts_search_criteria
  description:
schemes:
  - https
host: huaweicloud.com
tags:
  - name: LTS
paths:
  /v1.0/{project_id}/groups/{group_id}/topics/{topic_id}/search-criterias:
    post:
      tag: LTS
      operationId: CreateSearchCriterias
    get:
      tag: LTS
      operationId: ListCriterias
    delete:
      tag: LTS
      operationId: DeleteSearchCriterias
