info:
  version: v1.41.1
  title: resource_huaweicloud_obs_bucket_policy
  description:
schemes:
  - https
host: huaweicloud.com
tags:
  - name: OBS
paths:
  ?policy:
    put:
      tag: OBS
      operationId: SetBucketPolicy
    get:
      tag: OBS
      operationId: GetBucketPolicy
    delete:
      tag: OBS
      operationId: DeleteBucketPolicy
